@startuml wifi-scan
==trigger scan==
Settings -> WifiManager: startScan()
WifiManager -> WifiServiceImpl : startScan()
WifiServiceImpl -> ScanRequestProxy : startScan()
ScanRequestProxy -> WifiScanner : startScan()
WifiScanner -> WSSI.CH : CMD_START_SINGLE_SCAN
WSSI.CH -> WSSI.WSSSM : CMD_START_SINGLE_SCAN
WSSI.WSSSM -> WSSSM.DSS : CMD_START_SINGLE_SCAN
WSSSM.DSS -> WSSI.WSSSM : tryToStartNewScan()
WSSI.WSSSM -> WificondScannerImpl : startSingleScan()
WificondScannerImpl -> WifiNative : scan()
WifiNative -> WificondControl : scan()
WificondControl -> IWifiServiceImpl : scan()
==trigger scan==

==register callback==
WificondScannerImpl -> WifiMonitor : registerHandler(SCAN_RESULTS_EVENT)
WificondControl -> IWifiServiceImpl : subscribeScanEvents()
==register callback==

==get scan result==
IWifiServiceImpl -> WificondControl : OnScanResultReady()
WificondControl -> WifiMonitor : broadcastScanResultEvent()
WifiMonitor -> WificondScannerImpl : SCAN_RESULTS_EVENT
WificondScannerImpl -> WificondScannerImpl : pollLatestScanData()
WificondScannerImpl -> WSSI.WSSSM : onScanStatus()
WSSI.WSSSM -> WSSSM.ScanningState : CMD_SCAN_RESULTS_AVAILABLE
WSSSM.ScanningState -> WSSI.WSSSM : reportScanResults()
WSSI.WSSSM -> WifiScanner : CMD_SCAN_RESULT
WifiScanner -> ScanRequestProxy : onResults()
==get scan result==

@enduml
